FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Keda.Samples.DotNet.Web/Keda.Samples.DotNet.Web.csproj", "Keda.Samples.DotNet.Web/"]
COPY ["Keda.Samples.Dotnet.Contracts/Keda.Samples.Dotnet.Contracts.csproj", "Keda.Samples.Dotnet.Contracts/"]
RUN dotnet restore "Keda.Samples.DotNet.Web/Keda.Samples.DotNet.Web.csproj"
COPY . .
WORKDIR "/src/Keda.Samples.DotNet.Web"
RUN dotnet build "Keda.Samples.DotNet.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Keda.Samples.DotNet.Web.csproj" -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 8080
USER 1000
ENTRYPOINT ["dotnet", "Keda.Samples.DotNet.Web.dll"]
