version: '3.4'

services:
  keda.samples.worker.servicebus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrderQueueOptions__QueueName=orders

      # Authentication mode: Connection string
      - OrderQueueOptions__AuthMode=ConnectionString
      - OrderQueueOptions__ConnectionString=<connection-string>

      # Authentication mode: Service Principle
      # - OrderQueueOptions__AuthMode=ServicePrinciple
      # - OrderQueueOptions__FullyQualifiedNamespace=<service-bus-namespace>.servicebus.windows.net
      # - OrderQueueOptions__TenantId=<ad-tenant-id>
      # - OrderQueueOptions__ClientId=<ad-idenity-app-id>
      # - OrderQueueOptions__ClientSecret=<ad-idenity-app-secret>

      # Authentication mode: Managed Identity
      #- OrderQueueOptions__AuthMode=ManagedIdentity
      #- OrderQueueOptions__FullyQualifiedNamespace=<service-bus-namespace>.servicebus.windows.net
      #  Optionally specify ID of user-assigned application identity
      #- OrderQueueOptions__ClientId=<ad-idenity-app-id>
  keda.samples.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrderQueueOptions__AuthMode=ConnectionString
      - OrderQueueOptions__ConnectionString=<connection-string>
